name: Refresh coveo searchToken for docs dev/staging/production
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */23 * * *"

jobs:
  generate-coveo-search-token:
    name: Generate Coveo Search Tokens
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read # for 8398a7/action-slack
    strategy:
      matrix:
        include:
          - env_name: dev
            env_api_key: "COVEO_API_DEV"
            env_coveo_org_id: "f5networkx1h1607h"
          - env_name: staging
            env_api_key: "COVEO_API_STAGING"
            env_coveo_org_id: "f5networksnonproduction1xqykzabw"
          - env_name: prod
            env_api_key: "COVEO_API_PROD"
            env_coveo_org_id: "f5networksproduction5vkhn00h"
    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Generating token for ${{matrix.env_name}} ...
        id: generate-token
        continue-on-error: true
        env:
          COVEO_API_KEY: ${{secrets[matrix.env_api_key]}}
          COVEO_SEARCH_HUB: "HUB_ES_Nginx_Docs_And_Org"
        run: |
          RESPONSE=$(curl -w "\nHTTP_CODE: %{http_code}" -s -X POST "https://platform.cloud.coveo.com/rest/search/v2/token?organizationId=${{matrix.env_coveo_org_id}}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${COVEO_API_KEY}" \
          -d '{
              "searchHub": "'${COVEO_SEARCH_HUB}'",
              "organization": "'${{matrix.env_coveo_org_id}}'",
              "userIds": [
                  {
                  "type": "User",
                  "name": "anonymous",
                  "provider": "Email Security Provider"
                  }
              ]
              }')
          STATUS_CODE=$(echo "$RESPONSE" | grep HTTP_ | awk '{print $2}')
          SEARCH_TOKEN=$(echo "$RESPONSE" | sed '$d' | jq -r '.token')

          if [ $STATUS_CODE -ne 200 ]; then
            echo "Error: HTTP request failed with status $STATUS_CODE"
            echo "$RESPONSE"
            exit 1
          fi
          if [ "$SEARCH_TOKEN" == "null" ]; then
            echo "Error: Failed to extract search token from response"
            exit 1
          fi

          mkdir coveo/
          echo "{\"token\": \"$SEARCH_TOKEN\", \"org_id\": \"${{matrix.env_coveo_org_id}}\"}" > coveo/search_token.json

      - name: Upload token for ${{matrix.env_name}}
        if: ${{ steps.generate-token.outcome == 'success' }}
        uses: actions/upload-artifact@v5
        with:
          name: ${{matrix.env_name}}
          path: "./"

      - name: Send a notification if token generation step failed
        if: ${{ steps.generate-token.outcome == 'failure' }}
        uses: 8398a7/action-slack@77eaa4f1c608a7d68b38af4e3f739dcd8cba273e # v3.19.0
        with: 
          status: custom
          custom_payload: |
            {
                username: 'Github',
                mention: 'channel',
                attachments: [{
                  title: '[${{ github.event.repository.full_name }}] Coveo Token Generation Failed (${{matrix.env_name}} environment)',
                  color: 'danger',
                  fields: [{
                    title: 'Pipeline URL',
                    value: '<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>',
                    short: false
                  }]
                }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DOCS_INCIDENT }}
          

  push-tokens-to-azure:
    name: Batch push coveo search tokens to Azure
    runs-on: ubuntu-latest
    needs: generate-coveo-search-token
    steps:
      - name: Download Coveo search token
        uses: actions/download-artifact@v6

      - name: View files
        run: ls -R

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS_DOCS}}

      - name: Retrieve secrets from Keyvault
        id: keyvault
        uses: azure/cli@9f7ce6f37c31b777ec6c6b6d1dfe7db79f497956
        with:
          inlineScript: |
            secrets_get=(productionHostname previewHostname resourceGroupName cdnProfileName cdnName accountName)
            for secret_get in ${secrets_get[@]}
            do
              value=$(az keyvault secret show --name $secret_get --vault-name ${{ secrets.AZURE_KEY_VAULT_DOCS }} --query value --output tsv)
              echo "::add-mask::$value"
              echo "$secret_get=$value" >> $GITHUB_OUTPUT
            done

      - name: Push to Azure container storage
        run: |
          az storage blob upload-batch \
            -s ./ \
            -d '$web' \
            --account-name ${{steps.keyvault.outputs.accountName}} \
            --overwrite \
            --content-cache-control "no-store" \
            --auth-mode login

          az afd endpoint purge \
            --resource-group ${{steps.keyvault.outputs.resourceGroupName}} \
            --profile-name ${{steps.keyvault.outputs.cdnProfileName}} \
            --endpoint-name ${{steps.keyvault.outputs.cdnName}} \
            --domains docs.nginx.com docs-dev.nginx.com docs-staging.nginx.com \
            --content-paths '/.netlify/functions/*'
